### ISSUE TITLE
What font are you using in the screenshots?

### ISSUE THREAD

**Issue by rifazn** [Badacadabra/vim-archery#1]
Hope this isn't very inappropriate, but what's the font in the screenshots?

**Comment by AlphaTechnolog** [comment]
I think it's Anonymice Nerd Font

**Comment by Badacadabra** [comment]
Hello @rifazn, @AlphaTechnolog,

I apologize for the very late response.

It is hard to say after all these years... But at least on GVim, I was using [Larabie Font](https://www.dafont.com/larabie-font.font), as you can see here: https://github.com/Badacadabra/Vimpressionist/blob/master/vim/vimrc

Thanks for your patience! :+1:

**Comment by rifazn** [comment]
Ah, thanks!

And thanks too for putting your colorscheme out there! It was just what I needed at the time. Very much appreciated.
